# Generated by Django 3.1.1 on 2020-12-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=100)),
                ('cpu_cooler', models.CharField(max_length=100)),
                ('motherboard', models.CharField(max_length=100)),
                ('memory1', models.CharField(max_length=100)),
                ('memory2', models.CharField(max_length=100)),
                ('storage1', models.CharField(max_length=100)),
                ('storage2', models.CharField(max_length=100)),
                ('storage3', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('case', models.CharField(max_length=100)),
                ('psu', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('monitor1', models.CharField(max_length=100)),
                ('monitor2', models.CharField(max_length=100)),
                ('monitor3', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
