# Generated by Django 3.1.1 on 2020-12-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_build_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='memory2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='monitor1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='monitor2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='monitor3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='storage2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='storage3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
