# Generated by Django 3.1.4 on 2021-02-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_case_cpu_cpu_cooler_gpu_memory1_memory2_monitor1_monitor2_monitor3_motherboard_os_psu_storage1_stora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Os',
        ),
    ]
